import os
import sipconfig
from PyQt4 import pyqtconfig

# The name of the SIP build file generated by SIP and used by the build
# system.
workdir = "generated"
build_file = "ts.sbf"

# Get the PyQt configuration information.
config = pyqtconfig.Configuration()

home		= os.path.expanduser('~')
install_dir	= home + '/usr/python'
prj_dir		= os.getcwd() + '/..'
include_dir	= prj_dir + '/include'
ui_include_dir	= prj_dir + '/ui_include'
lib_dir		= prj_dir + '/lib'

# Get the extra SIP flags needed by the imported qt module.  Note that
# this normally only includes those flags (-x and -t) that relate to SIP's
# versioning system.
qt_sip_flags = config.pyqt_sip_flags

# Run SIP to generate the code.  Note that we tell SIP where to find the qt
# module's specification files using the -I flag.
command = " ".join([config.sip_bin, "-c", workdir, "-b", workdir + "/" + build_file, "-I", config.pyqt_sip_dir, qt_sip_flags, "ts.sip"])
print command
os.system(command)
# We are going to install the SIP specification file for this module and
# its configuration module.
installs = []

# installs.append(["data.sip", os.path.join(config.default_sip_dir, "data")])

# installs.append(["dataconfig.py", config.default_mod_dir])

installs.append(["../__init__.py", install_dir ])

# Create the Makefile.  The QtModuleMakefile class provided by the
# pyqtconfig module takes care of all the extra preprocessor, compiler and
# linker flags needed by the Qt library.
makefile = pyqtconfig.QtCoreModuleMakefile(
    configuration=config,
    build_file=build_file,
    install_dir=install_dir,
    installs=installs,
    dir=workdir,
    qt=['QtCore', 'QtGui', 'QtSql', 'QtXml' ]
)

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = [ "componentes" ]
makefile.extra_include_dirs = [ include_dir, ui_include_dir ]
makefile.extra_lib_dirs = [ lib_dir ]

# Generate the Makefile itself.
makefile.generate()

# Now we create the configuration module.  This is done by merging a Python
# dictionary (whose values are normally determined dynamically) with a
# (static) template.
content = {
    # Publish where the SIP specifications for this module will be
    # installed.
    "ts_sip_dir":    config.default_sip_dir,

    # Publish the set of SIP flags needed by this module.  As these are the
    # same flags needed by the qt module we could leave it out, but this
    # allows us to change the flags at a later date without breaking
    # scripts that import the configuration module.
    "ts_sip_flags":  qt_sip_flags
}

# This creates the helloconfig.py module from the helloconfig.py.in
# template and the dictionary.
sipconfig.create_config_module("tsconfig.py", "tsconfig.py.in", content)
