/*****************************************************************************
  TRUST COMPONENTS
  
  (C) Trustserver S. L., 2009
  
  Todos los derechos reservados.
  
  $Id: ts.sip 215 2010-04-06 12:30:04Z bruno $
  $URL: https://svn.trustserver.net/svn/trabajo/componentes/trunk/sip/ts.sip $
*****************************************************************************/

%Module ts 0

%Import QtCore/QtCoremod.sip
%Import QtSql/QtSqlmod.sip
%Import QtGui/QtGuimod.sip
%Import QtXml/QtXmlmod.sip

%Include dimension.sip
%Include unit.sip
%Include unitcollection.sip
%Include unitsystem.sip
%Include magnitude.sip
%Include combodatamodel.sip
%Include baseforeignkey.sip
%Include fkmodel.sip
%Include foreignkey.sip
%Include rowcontrolchild.sip
%Include rowcontrol.sip
%Include rowcontrolchildcolumnproxy.sip
%Include relone2one.sip
%Include relone2oneproxy.sip
%Include seqtablemodel.sip
%Include datadialog.sip
%Include tcombobox.sip
%Include dimensionedit.sip
%Include fkitemdelegate.sip
%Include ttabwidget.sip
%Include tsqlbuttonbox.sip
%Include ttableview.sip
%Include tsqltablenavigator.sip


