# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listadoresultadosdlg.ui'
#
# Created: Fri Feb 21 12:06:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ListadoResultadosDlgClass(object):
    def setupUi(self, ListadoResultadosDlgClass):
        ListadoResultadosDlgClass.setObjectName(_fromUtf8("ListadoResultadosDlgClass"))
        ListadoResultadosDlgClass.resize(489, 199)
        self.verticalLayout = QtGui.QVBoxLayout(ListadoResultadosDlgClass)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(ListadoResultadosDlgClass)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.escenario = TComboBox(ListadoResultadosDlgClass)
        self.escenario.setObjectName(_fromUtf8("escenario"))
        self.horizontalLayout_5.addWidget(self.escenario)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 4)
        self.label = QtGui.QLabel(ListadoResultadosDlgClass)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.agregaContaminante = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.agregaContaminante.setChecked(False)
        self.agregaContaminante.setObjectName(_fromUtf8("agregaContaminante"))
        self.gridLayout.addWidget(self.agregaContaminante, 1, 1, 1, 1)
        self.todosContaminante = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.todosContaminante.setObjectName(_fromUtf8("todosContaminante"))
        self.gridLayout.addWidget(self.todosContaminante, 1, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.soloContaminante = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.soloContaminante.setObjectName(_fromUtf8("soloContaminante"))
        self.horizontalLayout.addWidget(self.soloContaminante)
        self.contaminante = TComboBox(ListadoResultadosDlgClass)
        self.contaminante.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contaminante.sizePolicy().hasHeightForWidth())
        self.contaminante.setSizePolicy(sizePolicy)
        self.contaminante.setObjectName(_fromUtf8("contaminante"))
        self.horizontalLayout.addWidget(self.contaminante)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 4, 1, 1)
        self.label_2 = QtGui.QLabel(ListadoResultadosDlgClass)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.agregaFuente = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.agregaFuente.setChecked(False)
        self.agregaFuente.setObjectName(_fromUtf8("agregaFuente"))
        self.gridLayout.addWidget(self.agregaFuente, 2, 1, 1, 1)
        self.todosFuente = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.todosFuente.setObjectName(_fromUtf8("todosFuente"))
        self.gridLayout.addWidget(self.todosFuente, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.soloFuente = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.soloFuente.setObjectName(_fromUtf8("soloFuente"))
        self.horizontalLayout_2.addWidget(self.soloFuente)
        self.fuente = TComboBox(ListadoResultadosDlgClass)
        self.fuente.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuente.sizePolicy().hasHeightForWidth())
        self.fuente.setSizePolicy(sizePolicy)
        self.fuente.setObjectName(_fromUtf8("fuente"))
        self.horizontalLayout_2.addWidget(self.fuente)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 4, 1, 1)
        self.label_3 = QtGui.QLabel(ListadoResultadosDlgClass)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.agregaZona = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.agregaZona.setChecked(False)
        self.agregaZona.setObjectName(_fromUtf8("agregaZona"))
        self.gridLayout.addWidget(self.agregaZona, 3, 1, 1, 1)
        self.todosZona = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.todosZona.setObjectName(_fromUtf8("todosZona"))
        self.gridLayout.addWidget(self.todosZona, 3, 2, 1, 1)
        self.nivelZona = TComboBox(ListadoResultadosDlgClass)
        self.nivelZona.setEnabled(False)
        self.nivelZona.setObjectName(_fromUtf8("nivelZona"))
        self.gridLayout.addWidget(self.nivelZona, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.soloZona = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.soloZona.setObjectName(_fromUtf8("soloZona"))
        self.horizontalLayout_3.addWidget(self.soloZona)
        self.zona = TComboBox(ListadoResultadosDlgClass)
        self.zona.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zona.sizePolicy().hasHeightForWidth())
        self.zona.setSizePolicy(sizePolicy)
        self.zona.setObjectName(_fromUtf8("zona"))
        self.horizontalLayout_3.addWidget(self.zona)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 4, 1, 1)
        self.label_4 = QtGui.QLabel(ListadoResultadosDlgClass)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.agregaClasificacion = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.agregaClasificacion.setChecked(True)
        self.agregaClasificacion.setObjectName(_fromUtf8("agregaClasificacion"))
        self.gridLayout.addWidget(self.agregaClasificacion, 4, 1, 1, 1)
        self.todosClasificacion = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.todosClasificacion.setObjectName(_fromUtf8("todosClasificacion"))
        self.gridLayout.addWidget(self.todosClasificacion, 4, 2, 1, 1)
        self.nivelClasificacion = TComboBox(ListadoResultadosDlgClass)
        self.nivelClasificacion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nivelClasificacion.sizePolicy().hasHeightForWidth())
        self.nivelClasificacion.setSizePolicy(sizePolicy)
        self.nivelClasificacion.setObjectName(_fromUtf8("nivelClasificacion"))
        self.gridLayout.addWidget(self.nivelClasificacion, 4, 3, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.soloClasificacion = QtGui.QRadioButton(ListadoResultadosDlgClass)
        self.soloClasificacion.setObjectName(_fromUtf8("soloClasificacion"))
        self.horizontalLayout_4.addWidget(self.soloClasificacion)
        self.clasificacion = TComboBox(ListadoResultadosDlgClass)
        self.clasificacion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clasificacion.sizePolicy().hasHeightForWidth())
        self.clasificacion.setSizePolicy(sizePolicy)
        self.clasificacion.setObjectName(_fromUtf8("clasificacion"))
        self.horizontalLayout_4.addWidget(self.clasificacion)
        self.horizontalLayout_4.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtGui.QDialogButtonBox(ListadoResultadosDlgClass)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.agregaContaminante)
        self.label_2.setBuddy(self.agregaFuente)
        self.label_3.setBuddy(self.agregaZona)
        self.label_4.setBuddy(self.agregaClasificacion)

        self.retranslateUi(ListadoResultadosDlgClass)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ListadoResultadosDlgClass.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ListadoResultadosDlgClass.reject)
        QtCore.QObject.connect(self.soloContaminante, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contaminante.setEnabled)
        QtCore.QObject.connect(self.soloFuente, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fuente.setEnabled)
        QtCore.QObject.connect(self.soloZona, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.zona.setEnabled)
        QtCore.QObject.connect(self.soloClasificacion, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clasificacion.setEnabled)
        QtCore.QObject.connect(self.agregaZona, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.nivelZona.setDisabled)
        QtCore.QObject.connect(self.agregaClasificacion, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.nivelClasificacion.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(ListadoResultadosDlgClass)
        ListadoResultadosDlgClass.setTabOrder(self.agregaContaminante, self.todosContaminante)
        ListadoResultadosDlgClass.setTabOrder(self.todosContaminante, self.soloContaminante)
        ListadoResultadosDlgClass.setTabOrder(self.soloContaminante, self.contaminante)
        ListadoResultadosDlgClass.setTabOrder(self.contaminante, self.agregaFuente)
        ListadoResultadosDlgClass.setTabOrder(self.agregaFuente, self.todosFuente)
        ListadoResultadosDlgClass.setTabOrder(self.todosFuente, self.soloFuente)
        ListadoResultadosDlgClass.setTabOrder(self.soloFuente, self.fuente)
        ListadoResultadosDlgClass.setTabOrder(self.fuente, self.agregaZona)
        ListadoResultadosDlgClass.setTabOrder(self.agregaZona, self.todosZona)
        ListadoResultadosDlgClass.setTabOrder(self.todosZona, self.nivelZona)
        ListadoResultadosDlgClass.setTabOrder(self.nivelZona, self.soloZona)
        ListadoResultadosDlgClass.setTabOrder(self.soloZona, self.zona)
        ListadoResultadosDlgClass.setTabOrder(self.zona, self.agregaClasificacion)
        ListadoResultadosDlgClass.setTabOrder(self.agregaClasificacion, self.todosClasificacion)
        ListadoResultadosDlgClass.setTabOrder(self.todosClasificacion, self.nivelClasificacion)
        ListadoResultadosDlgClass.setTabOrder(self.nivelClasificacion, self.soloClasificacion)
        ListadoResultadosDlgClass.setTabOrder(self.soloClasificacion, self.clasificacion)
        ListadoResultadosDlgClass.setTabOrder(self.clasificacion, self.buttonBox)

    def retranslateUi(self, ListadoResultadosDlgClass):
        ListadoResultadosDlgClass.setWindowTitle(_translate("ListadoResultadosDlgClass", "Seleccione el listado...", None))
        self.label_5.setText(_translate("ListadoResultadosDlgClass", "Escenario", None))
        self.label.setText(_translate("ListadoResultadosDlgClass", "Contaminante", None))
        self.agregaContaminante.setText(_translate("ListadoResultadosDlgClass", "Agregar equiv.", None))
        self.todosContaminante.setText(_translate("ListadoResultadosDlgClass", "Todos", None))
        self.soloContaminante.setText(_translate("ListadoResultadosDlgClass", "Sólo", None))
        self.label_2.setText(_translate("ListadoResultadosDlgClass", "Fuente", None))
        self.agregaFuente.setText(_translate("ListadoResultadosDlgClass", "Agregar", None))
        self.todosFuente.setText(_translate("ListadoResultadosDlgClass", "Todos", None))
        self.soloFuente.setText(_translate("ListadoResultadosDlgClass", "Sólo", None))
        self.label_3.setText(_translate("ListadoResultadosDlgClass", "Zona", None))
        self.agregaZona.setText(_translate("ListadoResultadosDlgClass", "Agregar", None))
        self.todosZona.setText(_translate("ListadoResultadosDlgClass", "Todos", None))
        self.soloZona.setText(_translate("ListadoResultadosDlgClass", "Sólo", None))
        self.label_4.setText(_translate("ListadoResultadosDlgClass", "Clasificación", None))
        self.agregaClasificacion.setText(_translate("ListadoResultadosDlgClass", "Agregar", None))
        self.todosClasificacion.setText(_translate("ListadoResultadosDlgClass", "Todos", None))
        self.soloClasificacion.setText(_translate("ListadoResultadosDlgClass", "Sólo", None))

from ts import TComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ListadoResultadosDlgClass = QtGui.QDialog()
    ui = Ui_ListadoResultadosDlgClass()
    ui.setupUi(ListadoResultadosDlgClass)
    ListadoResultadosDlgClass.show()
    sys.exit(app.exec_())

