# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maparesultadosdlg.ui'
#
# Created: Fri Feb 21 12:06:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapaResultadosDlgClass(object):
    def setupUi(self, MapaResultadosDlgClass):
        MapaResultadosDlgClass.setObjectName(_fromUtf8("MapaResultadosDlgClass"))
        MapaResultadosDlgClass.resize(363, 229)
        self.verticalLayout = QtGui.QVBoxLayout(MapaResultadosDlgClass)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(MapaResultadosDlgClass)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.escenario = TComboBox(MapaResultadosDlgClass)
        self.escenario.setObjectName(_fromUtf8("escenario"))
        self.horizontalLayout_5.addWidget(self.escenario)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(MapaResultadosDlgClass)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.nivelZona = TComboBox(MapaResultadosDlgClass)
        self.nivelZona.setEnabled(True)
        self.nivelZona.setObjectName(_fromUtf8("nivelZona"))
        self.horizontalLayout_3.addWidget(self.nivelZona)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.label = QtGui.QLabel(MapaResultadosDlgClass)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.agregaContaminante = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.agregaContaminante.setChecked(False)
        self.agregaContaminante.setObjectName(_fromUtf8("agregaContaminante"))
        self.gridLayout.addWidget(self.agregaContaminante, 2, 1, 1, 1)
        self.soloContaminante = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.soloContaminante.setObjectName(_fromUtf8("soloContaminante"))
        self.gridLayout.addWidget(self.soloContaminante, 2, 2, 1, 1)
        self.contaminante = TComboBox(MapaResultadosDlgClass)
        self.contaminante.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contaminante.sizePolicy().hasHeightForWidth())
        self.contaminante.setSizePolicy(sizePolicy)
        self.contaminante.setObjectName(_fromUtf8("contaminante"))
        self.gridLayout.addWidget(self.contaminante, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(MapaResultadosDlgClass)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.agregaFuente = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.agregaFuente.setChecked(False)
        self.agregaFuente.setObjectName(_fromUtf8("agregaFuente"))
        self.gridLayout.addWidget(self.agregaFuente, 3, 1, 1, 1)
        self.soloFuente = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.soloFuente.setObjectName(_fromUtf8("soloFuente"))
        self.gridLayout.addWidget(self.soloFuente, 3, 2, 1, 1)
        self.fuente = TComboBox(MapaResultadosDlgClass)
        self.fuente.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fuente.sizePolicy().hasHeightForWidth())
        self.fuente.setSizePolicy(sizePolicy)
        self.fuente.setObjectName(_fromUtf8("fuente"))
        self.gridLayout.addWidget(self.fuente, 3, 3, 1, 1)
        self.label_4 = QtGui.QLabel(MapaResultadosDlgClass)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.agregaClasificacion = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.agregaClasificacion.setChecked(True)
        self.agregaClasificacion.setObjectName(_fromUtf8("agregaClasificacion"))
        self.gridLayout.addWidget(self.agregaClasificacion, 4, 1, 1, 1)
        self.soloClasificacion = QtGui.QRadioButton(MapaResultadosDlgClass)
        self.soloClasificacion.setObjectName(_fromUtf8("soloClasificacion"))
        self.gridLayout.addWidget(self.soloClasificacion, 4, 2, 1, 1)
        self.nivelClasificacion = TComboBox(MapaResultadosDlgClass)
        self.nivelClasificacion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nivelClasificacion.sizePolicy().hasHeightForWidth())
        self.nivelClasificacion.setSizePolicy(sizePolicy)
        self.nivelClasificacion.setObjectName(_fromUtf8("nivelClasificacion"))
        self.gridLayout.addWidget(self.nivelClasificacion, 4, 3, 1, 1)
        self.clasificacion = TComboBox(MapaResultadosDlgClass)
        self.clasificacion.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clasificacion.sizePolicy().hasHeightForWidth())
        self.clasificacion.setSizePolicy(sizePolicy)
        self.clasificacion.setObjectName(_fromUtf8("clasificacion"))
        self.gridLayout.addWidget(self.clasificacion, 5, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.comboColor = QtGui.QComboBox(MapaResultadosDlgClass)
        self.comboColor.setObjectName(_fromUtf8("comboColor"))
        self.horizontalLayout.addWidget(self.comboColor)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(MapaResultadosDlgClass)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem3 = QtGui.QSpacerItem(20, 16, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(MapaResultadosDlgClass)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_5.setBuddy(self.escenario)
        self.label_3.setBuddy(self.nivelZona)
        self.label.setBuddy(self.agregaContaminante)
        self.label_2.setBuddy(self.agregaFuente)
        self.label_4.setBuddy(self.agregaClasificacion)
        self.label_6.setBuddy(self.comboColor)

        self.retranslateUi(MapaResultadosDlgClass)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MapaResultadosDlgClass.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MapaResultadosDlgClass.reject)
        QtCore.QObject.connect(self.soloContaminante, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.contaminante.setEnabled)
        QtCore.QObject.connect(self.soloFuente, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fuente.setEnabled)
        QtCore.QObject.connect(self.soloClasificacion, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.clasificacion.setEnabled)
        QtCore.QObject.connect(self.soloClasificacion, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.nivelClasificacion.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MapaResultadosDlgClass)
        MapaResultadosDlgClass.setTabOrder(self.escenario, self.nivelZona)
        MapaResultadosDlgClass.setTabOrder(self.nivelZona, self.comboColor)
        MapaResultadosDlgClass.setTabOrder(self.comboColor, self.agregaContaminante)
        MapaResultadosDlgClass.setTabOrder(self.agregaContaminante, self.soloContaminante)
        MapaResultadosDlgClass.setTabOrder(self.soloContaminante, self.contaminante)
        MapaResultadosDlgClass.setTabOrder(self.contaminante, self.agregaFuente)
        MapaResultadosDlgClass.setTabOrder(self.agregaFuente, self.soloFuente)
        MapaResultadosDlgClass.setTabOrder(self.soloFuente, self.fuente)
        MapaResultadosDlgClass.setTabOrder(self.fuente, self.agregaClasificacion)
        MapaResultadosDlgClass.setTabOrder(self.agregaClasificacion, self.soloClasificacion)
        MapaResultadosDlgClass.setTabOrder(self.soloClasificacion, self.nivelClasificacion)
        MapaResultadosDlgClass.setTabOrder(self.nivelClasificacion, self.clasificacion)
        MapaResultadosDlgClass.setTabOrder(self.clasificacion, self.buttonBox)

    def retranslateUi(self, MapaResultadosDlgClass):
        MapaResultadosDlgClass.setWindowTitle(_translate("MapaResultadosDlgClass", "Seleccione el listado...", None))
        self.label_5.setText(_translate("MapaResultadosDlgClass", "Escenario", None))
        self.label_3.setText(_translate("MapaResultadosDlgClass", "Zona", None))
        self.label.setText(_translate("MapaResultadosDlgClass", "Contaminante", None))
        self.agregaContaminante.setText(_translate("MapaResultadosDlgClass", "Agregar equiv.", None))
        self.soloContaminante.setText(_translate("MapaResultadosDlgClass", "Sólo", None))
        self.label_2.setText(_translate("MapaResultadosDlgClass", "Fuente", None))
        self.agregaFuente.setText(_translate("MapaResultadosDlgClass", "Agregar", None))
        self.soloFuente.setText(_translate("MapaResultadosDlgClass", "Sólo", None))
        self.label_4.setText(_translate("MapaResultadosDlgClass", "Clasificación", None))
        self.agregaClasificacion.setText(_translate("MapaResultadosDlgClass", "Agregar", None))
        self.soloClasificacion.setText(_translate("MapaResultadosDlgClass", "Sólo", None))
        self.label_6.setText(_translate("MapaResultadosDlgClass", "Colores", None))

from ts import TComboBox

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MapaResultadosDlgClass = QtGui.QDialog()
    ui = Ui_MapaResultadosDlgClass()
    ui.setupUi(MapaResultadosDlgClass)
    MapaResultadosDlgClass.show()
    sys.exit(app.exec_())

