# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PyQt6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PyQt6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QWidget)

class Ui_MainWindowClass(object):
    def setupUi(self, MainWindowClass):
        if not MainWindowClass.objectName():
            MainWindowClass.setObjectName(u"MainWindowClass")
        MainWindowClass.resize(800, 600)
        self.actionQuit = QAction(MainWindowClass)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionOpenConnection = QAction(MainWindowClass)
        self.actionOpenConnection.setObjectName(u"actionOpenConnection")
        self.actionPreferencias = QAction(MainWindowClass)
        self.actionPreferencias.setObjectName(u"actionPreferencias")
        self.actionCopiar = QAction(MainWindowClass)
        self.actionCopiar.setObjectName(u"actionCopiar")
        self.actionMotoresCalculo = QAction(MainWindowClass)
        self.actionMotoresCalculo.setObjectName(u"actionMotoresCalculo")
        self.actionMotoresCalculo.setCheckable(True)
        self.actionZonas = QAction(MainWindowClass)
        self.actionZonas.setObjectName(u"actionZonas")
        self.actionZonas.setCheckable(True)
        self.actionEscenario = QAction(MainWindowClass)
        self.actionEscenario.setObjectName(u"actionEscenario")
        self.actionEscenario.setCheckable(True)
        self.actionOrigen = QAction(MainWindowClass)
        self.actionOrigen.setObjectName(u"actionOrigen")
        self.actionOrigen.setCheckable(True)
        self.actionFuente = QAction(MainWindowClass)
        self.actionFuente.setObjectName(u"actionFuente")
        self.actionFuente.setCheckable(True)
        self.actionTipo_Clasificaci_n = QAction(MainWindowClass)
        self.actionTipo_Clasificaci_n.setObjectName(u"actionTipo_Clasificaci_n")
        self.actionTipo_Clasificaci_n.setCheckable(True)
        self.actionEquivalentes = QAction(MainWindowClass)
        self.actionEquivalentes.setObjectName(u"actionEquivalentes")
        self.actionEquivalentes.setCheckable(True)
        self.actionContaminante = QAction(MainWindowClass)
        self.actionContaminante.setObjectName(u"actionContaminante")
        self.actionContaminante.setCheckable(True)
        self.actionFuenteClasificacion = QAction(MainWindowClass)
        self.actionFuenteClasificacion.setObjectName(u"actionFuenteClasificacion")
        self.actionFuenteClasificacion.setCheckable(True)
        self.actionAforo = QAction(MainWindowClass)
        self.actionAforo.setObjectName(u"actionAforo")
        self.actionAforo.setCheckable(True)
        self.actionPlantillas = QAction(MainWindowClass)
        self.actionPlantillas.setObjectName(u"actionPlantillas")
        self.actionPlantillas.setCheckable(True)
        self.actionTablas = QAction(MainWindowClass)
        self.actionTablas.setObjectName(u"actionTablas")
        self.actionTablas.setCheckable(True)
        self.actionGraficos = QAction(MainWindowClass)
        self.actionGraficos.setObjectName(u"actionGraficos")
        self.actionGraficos.setCheckable(True)
        self.actionGenerar_PDF = QAction(MainWindowClass)
        self.actionGenerar_PDF.setObjectName(u"actionGenerar_PDF")
        self.actionFactor_Conversi_n = QAction(MainWindowClass)
        self.actionFactor_Conversi_n.setObjectName(u"actionFactor_Conversi_n")
        self.actionFactor_Conversi_n.setCheckable(True)
        self.actionFactor_Conversi_n_por_Aforo = QAction(MainWindowClass)
        self.actionFactor_Conversi_n_por_Aforo.setObjectName(u"actionFactor_Conversi_n_por_Aforo")
        self.actionFactor_Conversi_n_por_Aforo.setCheckable(True)
        self.actionValor_Dato = QAction(MainWindowClass)
        self.actionValor_Dato.setObjectName(u"actionValor_Dato")
        self.actionValor_Dato.setCheckable(True)
        self.actionContaminante_Aforo = QAction(MainWindowClass)
        self.actionContaminante_Aforo.setObjectName(u"actionContaminante_Aforo")
        self.actionContaminante_Aforo.setCheckable(True)
        self.actionMapAforoZona = QAction(MainWindowClass)
        self.actionMapAforoZona.setObjectName(u"actionMapAforoZona")
        self.actionMapAforoZona.setCheckable(True)
        self.actionContaminanteZona = QAction(MainWindowClass)
        self.actionContaminanteZona.setObjectName(u"actionContaminanteZona")
        self.actionContaminanteZona.setCheckable(True)
        self.actionArbolClasificacion = QAction(MainWindowClass)
        self.actionArbolClasificacion.setObjectName(u"actionArbolClasificacion")
        self.actionArbolClasificacion.setCheckable(True)
        self.actionCalcularEscenario = QAction(MainWindowClass)
        self.actionCalcularEscenario.setObjectName(u"actionCalcularEscenario")
        self.actionResultados = QAction(MainWindowClass)
        self.actionResultados.setObjectName(u"actionResultados")
        self.actionCombustibles = QAction(MainWindowClass)
        self.actionCombustibles.setObjectName(u"actionCombustibles")
        self.actionCombustibles.setCheckable(True)
        self.actionMapas = QAction(MainWindowClass)
        self.actionMapas.setObjectName(u"actionMapas")
        self.actionPrint = QAction(MainWindowClass)
        self.actionPrint.setObjectName(u"actionPrint")
        self.capullo = QWidget(MainWindowClass)
        self.capullo.setObjectName(u"capullo")
        MainWindowClass.setCentralWidget(self.capullo)
        self.menuBar = QMenuBar(MainWindowClass)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 800, 24))
        self.menuArchivo = QMenu(self.menuBar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        self.menuEdici_n = QMenu(self.menuBar)
        self.menuEdici_n.setObjectName(u"menuEdici_n")
        self.menuVentanas = QMenu(self.menuBar)
        self.menuVentanas.setObjectName(u"menuVentanas")
        self.menuZonas = QMenu(self.menuBar)
        self.menuZonas.setObjectName(u"menuZonas")
        self.menuEscenario = QMenu(self.menuBar)
        self.menuEscenario.setObjectName(u"menuEscenario")
        self.menuInformes = QMenu(self.menuBar)
        self.menuInformes.setObjectName(u"menuInformes")
        self.menuDatos = QMenu(self.menuBar)
        self.menuDatos.setObjectName(u"menuDatos")
        self.menuContaminantes_2 = QMenu(self.menuBar)
        self.menuContaminantes_2.setObjectName(u"menuContaminantes_2")
        self.menuC_lculo = QMenu(self.menuBar)
        self.menuC_lculo.setObjectName(u"menuC_lculo")
        MainWindowClass.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuEdici_n.menuAction())
        self.menuBar.addAction(self.menuEscenario.menuAction())
        self.menuBar.addAction(self.menuContaminantes_2.menuAction())
        self.menuBar.addAction(self.menuZonas.menuAction())
        self.menuBar.addAction(self.menuDatos.menuAction())
        self.menuBar.addAction(self.menuC_lculo.menuAction())
        self.menuBar.addAction(self.menuInformes.menuAction())
        self.menuBar.addAction(self.menuVentanas.menuAction())
        self.menuArchivo.addAction(self.actionOpenConnection)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionPrint)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionQuit)
        self.menuEdici_n.addAction(self.actionCopiar)
        self.menuEdici_n.addSeparator()
        self.menuEdici_n.addAction(self.actionPreferencias)
        self.menuZonas.addAction(self.actionZonas)
        self.menuEscenario.addAction(self.actionEscenario)
        self.menuEscenario.addAction(self.actionFuente)
        self.menuEscenario.addAction(self.actionArbolClasificacion)
        self.menuEscenario.addAction(self.actionCombustibles)
        self.menuEscenario.addAction(self.actionMotoresCalculo)
        self.menuInformes.addAction(self.actionPlantillas)
        self.menuInformes.addAction(self.actionTablas)
        self.menuInformes.addAction(self.actionGraficos)
        self.menuDatos.addAction(self.actionContaminante_Aforo)
        self.menuDatos.addAction(self.actionContaminanteZona)
        self.menuContaminantes_2.addAction(self.actionContaminante)
        self.menuContaminantes_2.addAction(self.actionEquivalentes)
        self.menuContaminantes_2.addAction(self.actionFactor_Conversi_n)
        self.menuContaminantes_2.addAction(self.actionFactor_Conversi_n_por_Aforo)
        self.menuContaminantes_2.addAction(self.actionMapAforoZona)
        self.menuC_lculo.addAction(self.actionCalcularEscenario)
        self.menuC_lculo.addSeparator()
        self.menuC_lculo.addAction(self.actionResultados)
        self.menuC_lculo.addAction(self.actionMapas)

        self.retranslateUi(MainWindowClass)

        QMetaObject.connectSlotsByName(MainWindowClass)
    # setupUi

    def retranslateUi(self, MainWindowClass):
        MainWindowClass.setWindowTitle(QCoreApplication.translate("MainWindowClass", u"AIRE", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindowClass", u"Salir", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindowClass", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpenConnection.setText(QCoreApplication.translate("MainWindowClass", u"Abre conexi\u00f3n", None))
#if QT_CONFIG(shortcut)
        self.actionOpenConnection.setShortcut(QCoreApplication.translate("MainWindowClass", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferencias.setText(QCoreApplication.translate("MainWindowClass", u"Preferencias", None))
        self.actionCopiar.setText(QCoreApplication.translate("MainWindowClass", u"Copiar", None))
#if QT_CONFIG(shortcut)
        self.actionCopiar.setShortcut(QCoreApplication.translate("MainWindowClass", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionMotoresCalculo.setText(QCoreApplication.translate("MainWindowClass", u"Motores de c\u00e1lculo", None))
        self.actionZonas.setText(QCoreApplication.translate("MainWindowClass", u"Zonas", None))
        self.actionEscenario.setText(QCoreApplication.translate("MainWindowClass", u"Escenario", None))
        self.actionOrigen.setText(QCoreApplication.translate("MainWindowClass", u"Origen", None))
        self.actionFuente.setText(QCoreApplication.translate("MainWindowClass", u"Fuente", None))
        self.actionTipo_Clasificaci_n.setText(QCoreApplication.translate("MainWindowClass", u"Tipo Clasificaci\u00f3n", None))
        self.actionEquivalentes.setText(QCoreApplication.translate("MainWindowClass", u"Equivalentes", None))
        self.actionContaminante.setText(QCoreApplication.translate("MainWindowClass", u"Contaminante", None))
        self.actionFuenteClasificacion.setText(QCoreApplication.translate("MainWindowClass", u"Fuente Clasificacion", None))
        self.actionAforo.setText(QCoreApplication.translate("MainWindowClass", u"Aforo", None))
        self.actionPlantillas.setText(QCoreApplication.translate("MainWindowClass", u"Plantillas", None))
        self.actionTablas.setText(QCoreApplication.translate("MainWindowClass", u"Tablas", None))
        self.actionGraficos.setText(QCoreApplication.translate("MainWindowClass", u"Gr\u00e1ficos", None))
        self.actionGenerar_PDF.setText(QCoreApplication.translate("MainWindowClass", u"Generar PDF", None))
        self.actionFactor_Conversi_n.setText(QCoreApplication.translate("MainWindowClass", u"Factor Conversi\u00f3n", None))
        self.actionFactor_Conversi_n_por_Aforo.setText(QCoreApplication.translate("MainWindowClass", u"Factor Conversi\u00f3n por Aforo", None))
        self.actionValor_Dato.setText(QCoreApplication.translate("MainWindowClass", u"Toma en aforo", None))
        self.actionContaminante_Aforo.setText(QCoreApplication.translate("MainWindowClass", u"Contaminante en aforo", None))
        self.actionMapAforoZona.setText(QCoreApplication.translate("MainWindowClass", u"Factor por Aforo y Municipio", None))
        self.actionContaminanteZona.setText(QCoreApplication.translate("MainWindowClass", u"Contaminante en fuente", None))
        self.actionArbolClasificacion.setText(QCoreApplication.translate("MainWindowClass", u"\u00c1rbol Clasificacion", None))
        self.actionCalcularEscenario.setText(QCoreApplication.translate("MainWindowClass", u"Calcular escenario...", None))
        self.actionResultados.setText(QCoreApplication.translate("MainWindowClass", u"Resultados...", None))
        self.actionCombustibles.setText(QCoreApplication.translate("MainWindowClass", u"Combustibles", None))
        self.actionMapas.setText(QCoreApplication.translate("MainWindowClass", u"Mapas...", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindowClass", u"Imprimir...", None))
#if QT_CONFIG(shortcut)
        self.actionPrint.setShortcut(QCoreApplication.translate("MainWindowClass", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindowClass", u"Archivo", None))
        self.menuEdici_n.setTitle(QCoreApplication.translate("MainWindowClass", u"Edici\u00f3n", None))
        self.menuVentanas.setTitle(QCoreApplication.translate("MainWindowClass", u"Ventanas", None))
        self.menuZonas.setTitle(QCoreApplication.translate("MainWindowClass", u"Zonas", None))
        self.menuEscenario.setTitle(QCoreApplication.translate("MainWindowClass", u"Maestro", None))
        self.menuInformes.setTitle(QCoreApplication.translate("MainWindowClass", u"Informes", None))
        self.menuDatos.setTitle(QCoreApplication.translate("MainWindowClass", u"Datos", None))
        self.menuContaminantes_2.setTitle(QCoreApplication.translate("MainWindowClass", u"Contaminantes", None))
        self.menuC_lculo.setTitle(QCoreApplication.translate("MainWindowClass", u"C\u00e1lculo", None))
    # retranslateUi

