# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapdatocontaminantelist.ui'
#
# Created: Fri Feb 21 12:06:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapDatoContaminanteListClass(object):
    def setupUi(self, MapDatoContaminanteListClass):
        MapDatoContaminanteListClass.setObjectName(_fromUtf8("MapDatoContaminanteListClass"))
        MapDatoContaminanteListClass.resize(513, 363)
        self.verticalLayout_5 = QtGui.QVBoxLayout(MapDatoContaminanteListClass)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(MapDatoContaminanteListClass)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tablaEscenario = QtGui.QTableView(self.tab)
        self.tablaEscenario.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaEscenario.setAlternatingRowColors(True)
        self.tablaEscenario.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaEscenario.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaEscenario.setObjectName(_fromUtf8("tablaEscenario"))
        self.verticalLayout_2.addWidget(self.tablaEscenario)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboTipoClasificacion = TComboBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboTipoClasificacion.sizePolicy().hasHeightForWidth())
        self.comboTipoClasificacion.setSizePolicy(sizePolicy)
        self.comboTipoClasificacion.setObjectName(_fromUtf8("comboTipoClasificacion"))
        self.horizontalLayout_2.addWidget(self.comboTipoClasificacion)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.arbolClasificacion = QtGui.QTreeView(self.tab_2)
        self.arbolClasificacion.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.arbolClasificacion.setAlternatingRowColors(True)
        self.arbolClasificacion.setObjectName(_fromUtf8("arbolClasificacion"))
        self.verticalLayout_3.addWidget(self.arbolClasificacion)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tablaMapClas = QtGui.QTableView(self.tab_5)
        self.tablaMapClas.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablaMapClas.setObjectName(_fromUtf8("tablaMapClas"))
        self.verticalLayout_6.addWidget(self.tablaMapClas)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.guardaMapClas = QtGui.QPushButton(self.tab_5)
        self.guardaMapClas.setObjectName(_fromUtf8("guardaMapClas"))
        self.horizontalLayout_3.addWidget(self.guardaMapClas)
        self.descartaMapClas = QtGui.QPushButton(self.tab_5)
        self.descartaMapClas.setObjectName(_fromUtf8("descartaMapClas"))
        self.horizontalLayout_3.addWidget(self.descartaMapClas)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.eliminaMapClas = QtGui.QPushButton(self.tab_5)
        self.eliminaMapClas.setObjectName(_fromUtf8("eliminaMapClas"))
        self.horizontalLayout_3.addWidget(self.eliminaMapClas)
        self.editaMapClas = QtGui.QPushButton(self.tab_5)
        self.editaMapClas.setObjectName(_fromUtf8("editaMapClas"))
        self.horizontalLayout_3.addWidget(self.editaMapClas)
        self.anadeMapClas = QtGui.QPushButton(self.tab_5)
        self.anadeMapClas.setObjectName(_fromUtf8("anadeMapClas"))
        self.horizontalLayout_3.addWidget(self.anadeMapClas)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tablaDato = QtGui.QTableView(self.tab_4)
        self.tablaDato.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablaDato.setAlternatingRowColors(True)
        self.tablaDato.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablaDato.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaDato.setObjectName(_fromUtf8("tablaDato"))
        self.verticalLayout_4.addWidget(self.tablaDato)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tablaMap = QtGui.QTableView(self.tab_3)
        self.tablaMap.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablaMap.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.tablaMap.setAlternatingRowColors(True)
        self.tablaMap.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablaMap.setObjectName(_fromUtf8("tablaMap"))
        self.verticalLayout.addWidget(self.tablaMap)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.guardar = QtGui.QPushButton(self.tab_3)
        self.guardar.setObjectName(_fromUtf8("guardar"))
        self.horizontalLayout.addWidget(self.guardar)
        self.descartar = QtGui.QPushButton(self.tab_3)
        self.descartar.setObjectName(_fromUtf8("descartar"))
        self.horizontalLayout.addWidget(self.descartar)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.elimina = QtGui.QPushButton(self.tab_3)
        self.elimina.setObjectName(_fromUtf8("elimina"))
        self.horizontalLayout.addWidget(self.elimina)
        self.edita = QtGui.QPushButton(self.tab_3)
        self.edita.setObjectName(_fromUtf8("edita"))
        self.horizontalLayout.addWidget(self.edita)
        self.anade = QtGui.QPushButton(self.tab_3)
        self.anade.setObjectName(_fromUtf8("anade"))
        self.horizontalLayout.addWidget(self.anade)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.clipboardMapDatoContaminante = QtGui.QAction(MapDatoContaminanteListClass)
        self.clipboardMapDatoContaminante.setObjectName(_fromUtf8("clipboardMapDatoContaminante"))
        self.label.setBuddy(self.comboTipoClasificacion)

        self.retranslateUi(MapDatoContaminanteListClass)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tablaMap, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MapDatoContaminanteListClass.showContextMenu)
        QtCore.QObject.connect(self.tablaMapClas, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), MapDatoContaminanteListClass.showContextMenu)
        QtCore.QMetaObject.connectSlotsByName(MapDatoContaminanteListClass)
        MapDatoContaminanteListClass.setTabOrder(self.tablaEscenario, self.tabWidget)
        MapDatoContaminanteListClass.setTabOrder(self.tabWidget, self.arbolClasificacion)
        MapDatoContaminanteListClass.setTabOrder(self.arbolClasificacion, self.comboTipoClasificacion)
        MapDatoContaminanteListClass.setTabOrder(self.comboTipoClasificacion, self.tablaMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.tablaMapClas, self.guardaMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.guardaMapClas, self.descartaMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.descartaMapClas, self.eliminaMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.eliminaMapClas, self.editaMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.editaMapClas, self.anadeMapClas)
        MapDatoContaminanteListClass.setTabOrder(self.anadeMapClas, self.tablaDato)
        MapDatoContaminanteListClass.setTabOrder(self.tablaDato, self.tablaMap)
        MapDatoContaminanteListClass.setTabOrder(self.tablaMap, self.guardar)
        MapDatoContaminanteListClass.setTabOrder(self.guardar, self.descartar)
        MapDatoContaminanteListClass.setTabOrder(self.descartar, self.elimina)
        MapDatoContaminanteListClass.setTabOrder(self.elimina, self.edita)
        MapDatoContaminanteListClass.setTabOrder(self.edita, self.anade)

    def retranslateUi(self, MapDatoContaminanteListClass):
        MapDatoContaminanteListClass.setWindowTitle(_translate("MapDatoContaminanteListClass", "Datos de conversión de contaminantes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MapDatoContaminanteListClass", "Escenario", None))
        self.label.setText(_translate("MapDatoContaminanteListClass", "Tipo de clasificación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MapDatoContaminanteListClass", "Clasificación", None))
        self.guardaMapClas.setText(_translate("MapDatoContaminanteListClass", "Guardar", None))
        self.descartaMapClas.setText(_translate("MapDatoContaminanteListClass", "Descartar", None))
        self.eliminaMapClas.setText(_translate("MapDatoContaminanteListClass", "Eliminar", None))
        self.editaMapClas.setText(_translate("MapDatoContaminanteListClass", "Editar", None))
        self.anadeMapClas.setText(_translate("MapDatoContaminanteListClass", "Añadir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MapDatoContaminanteListClass", "Fórmulas por clasificación", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MapDatoContaminanteListClass", "Dato", None))
        self.guardar.setText(_translate("MapDatoContaminanteListClass", "Guardar", None))
        self.descartar.setText(_translate("MapDatoContaminanteListClass", "Descartar", None))
        self.elimina.setText(_translate("MapDatoContaminanteListClass", "Eliminar", None))
        self.edita.setText(_translate("MapDatoContaminanteListClass", "Editar", None))
        self.anade.setText(_translate("MapDatoContaminanteListClass", "Añadir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MapDatoContaminanteListClass", "Fórmulas por dato", None))
        self.clipboardMapDatoContaminante.setText(_translate("MapDatoContaminanteListClass", "Inserta desde portapapeles", None))
        self.clipboardMapDatoContaminante.setToolTip(_translate("MapDatoContaminanteListClass", "Inserta desde portapapeles", None))

from ts import TComboBox
from widgets.datalist import DataList

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MapDatoContaminanteListClass = QtGui.DataList()
    ui = Ui_MapDatoContaminanteListClass()
    ui.setupUi(MapDatoContaminanteListClass)
    MapDatoContaminanteListClass.show()
    sys.exit(app.exec_())

