# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Feb 21 12:06:30 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowClass(object):
    def setupUi(self, MainWindowClass):
        MainWindowClass.setObjectName(_fromUtf8("MainWindowClass"))
        MainWindowClass.resize(800, 600)
        self.capullo = QtGui.QWidget(MainWindowClass)
        self.capullo.setObjectName(_fromUtf8("capullo"))
        MainWindowClass.setCentralWidget(self.capullo)
        self.menuBar = QtGui.QMenuBar(MainWindowClass)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArchivo = QtGui.QMenu(self.menuBar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuEdici_n = QtGui.QMenu(self.menuBar)
        self.menuEdici_n.setObjectName(_fromUtf8("menuEdici_n"))
        self.menuVentanas = QtGui.QMenu(self.menuBar)
        self.menuVentanas.setObjectName(_fromUtf8("menuVentanas"))
        self.menuZonas = QtGui.QMenu(self.menuBar)
        self.menuZonas.setObjectName(_fromUtf8("menuZonas"))
        self.menuEscenario = QtGui.QMenu(self.menuBar)
        self.menuEscenario.setObjectName(_fromUtf8("menuEscenario"))
        self.menuInformes = QtGui.QMenu(self.menuBar)
        self.menuInformes.setObjectName(_fromUtf8("menuInformes"))
        self.menuDatos = QtGui.QMenu(self.menuBar)
        self.menuDatos.setObjectName(_fromUtf8("menuDatos"))
        self.menuContaminantes_2 = QtGui.QMenu(self.menuBar)
        self.menuContaminantes_2.setObjectName(_fromUtf8("menuContaminantes_2"))
        self.menuC_lculo = QtGui.QMenu(self.menuBar)
        self.menuC_lculo.setObjectName(_fromUtf8("menuC_lculo"))
        MainWindowClass.setMenuBar(self.menuBar)
        self.actionQuit = QtGui.QAction(MainWindowClass)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpenConnection = QtGui.QAction(MainWindowClass)
        self.actionOpenConnection.setObjectName(_fromUtf8("actionOpenConnection"))
        self.actionPreferencias = QtGui.QAction(MainWindowClass)
        self.actionPreferencias.setObjectName(_fromUtf8("actionPreferencias"))
        self.actionCopiar = QtGui.QAction(MainWindowClass)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionMotoresCalculo = QtGui.QAction(MainWindowClass)
        self.actionMotoresCalculo.setCheckable(True)
        self.actionMotoresCalculo.setObjectName(_fromUtf8("actionMotoresCalculo"))
        self.actionZonas = QtGui.QAction(MainWindowClass)
        self.actionZonas.setCheckable(True)
        self.actionZonas.setObjectName(_fromUtf8("actionZonas"))
        self.actionEscenario = QtGui.QAction(MainWindowClass)
        self.actionEscenario.setCheckable(True)
        self.actionEscenario.setObjectName(_fromUtf8("actionEscenario"))
        self.actionOrigen = QtGui.QAction(MainWindowClass)
        self.actionOrigen.setCheckable(True)
        self.actionOrigen.setObjectName(_fromUtf8("actionOrigen"))
        self.actionFuente = QtGui.QAction(MainWindowClass)
        self.actionFuente.setCheckable(True)
        self.actionFuente.setObjectName(_fromUtf8("actionFuente"))
        self.actionTipo_Clasificaci_n = QtGui.QAction(MainWindowClass)
        self.actionTipo_Clasificaci_n.setCheckable(True)
        self.actionTipo_Clasificaci_n.setObjectName(_fromUtf8("actionTipo_Clasificaci_n"))
        self.actionEquivalentes = QtGui.QAction(MainWindowClass)
        self.actionEquivalentes.setCheckable(True)
        self.actionEquivalentes.setObjectName(_fromUtf8("actionEquivalentes"))
        self.actionContaminante = QtGui.QAction(MainWindowClass)
        self.actionContaminante.setCheckable(True)
        self.actionContaminante.setObjectName(_fromUtf8("actionContaminante"))
        self.actionFuenteClasificacion = QtGui.QAction(MainWindowClass)
        self.actionFuenteClasificacion.setCheckable(True)
        self.actionFuenteClasificacion.setObjectName(_fromUtf8("actionFuenteClasificacion"))
        self.actionAforo = QtGui.QAction(MainWindowClass)
        self.actionAforo.setCheckable(True)
        self.actionAforo.setObjectName(_fromUtf8("actionAforo"))
        self.actionPlantillas = QtGui.QAction(MainWindowClass)
        self.actionPlantillas.setCheckable(True)
        self.actionPlantillas.setObjectName(_fromUtf8("actionPlantillas"))
        self.actionTablas = QtGui.QAction(MainWindowClass)
        self.actionTablas.setCheckable(True)
        self.actionTablas.setObjectName(_fromUtf8("actionTablas"))
        self.actionGraficos = QtGui.QAction(MainWindowClass)
        self.actionGraficos.setCheckable(True)
        self.actionGraficos.setObjectName(_fromUtf8("actionGraficos"))
        self.actionGenerar_PDF = QtGui.QAction(MainWindowClass)
        self.actionGenerar_PDF.setObjectName(_fromUtf8("actionGenerar_PDF"))
        self.actionFactor_Conversi_n = QtGui.QAction(MainWindowClass)
        self.actionFactor_Conversi_n.setCheckable(True)
        self.actionFactor_Conversi_n.setObjectName(_fromUtf8("actionFactor_Conversi_n"))
        self.actionFactor_Conversi_n_por_Aforo = QtGui.QAction(MainWindowClass)
        self.actionFactor_Conversi_n_por_Aforo.setCheckable(True)
        self.actionFactor_Conversi_n_por_Aforo.setObjectName(_fromUtf8("actionFactor_Conversi_n_por_Aforo"))
        self.actionValor_Dato = QtGui.QAction(MainWindowClass)
        self.actionValor_Dato.setCheckable(True)
        self.actionValor_Dato.setObjectName(_fromUtf8("actionValor_Dato"))
        self.actionContaminante_Aforo = QtGui.QAction(MainWindowClass)
        self.actionContaminante_Aforo.setCheckable(True)
        self.actionContaminante_Aforo.setObjectName(_fromUtf8("actionContaminante_Aforo"))
        self.actionMapAforoZona = QtGui.QAction(MainWindowClass)
        self.actionMapAforoZona.setCheckable(True)
        self.actionMapAforoZona.setObjectName(_fromUtf8("actionMapAforoZona"))
        self.actionContaminanteZona = QtGui.QAction(MainWindowClass)
        self.actionContaminanteZona.setCheckable(True)
        self.actionContaminanteZona.setObjectName(_fromUtf8("actionContaminanteZona"))
        self.actionArbolClasificacion = QtGui.QAction(MainWindowClass)
        self.actionArbolClasificacion.setCheckable(True)
        self.actionArbolClasificacion.setObjectName(_fromUtf8("actionArbolClasificacion"))
        self.actionCalcularEscenario = QtGui.QAction(MainWindowClass)
        self.actionCalcularEscenario.setObjectName(_fromUtf8("actionCalcularEscenario"))
        self.actionResultados = QtGui.QAction(MainWindowClass)
        self.actionResultados.setObjectName(_fromUtf8("actionResultados"))
        self.actionCombustibles = QtGui.QAction(MainWindowClass)
        self.actionCombustibles.setCheckable(True)
        self.actionCombustibles.setObjectName(_fromUtf8("actionCombustibles"))
        self.actionMapas = QtGui.QAction(MainWindowClass)
        self.actionMapas.setObjectName(_fromUtf8("actionMapas"))
        self.actionPrint = QtGui.QAction(MainWindowClass)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.menuArchivo.addAction(self.actionOpenConnection)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionPrint)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionQuit)
        self.menuEdici_n.addAction(self.actionCopiar)
        self.menuEdici_n.addSeparator()
        self.menuEdici_n.addAction(self.actionPreferencias)
        self.menuZonas.addAction(self.actionZonas)
        self.menuEscenario.addAction(self.actionEscenario)
        self.menuEscenario.addAction(self.actionFuente)
        self.menuEscenario.addAction(self.actionArbolClasificacion)
        self.menuEscenario.addAction(self.actionCombustibles)
        self.menuEscenario.addAction(self.actionMotoresCalculo)
        self.menuInformes.addAction(self.actionPlantillas)
        self.menuInformes.addAction(self.actionTablas)
        self.menuInformes.addAction(self.actionGraficos)
        self.menuDatos.addAction(self.actionContaminante_Aforo)
        self.menuDatos.addAction(self.actionContaminanteZona)
        self.menuContaminantes_2.addAction(self.actionContaminante)
        self.menuContaminantes_2.addAction(self.actionEquivalentes)
        self.menuContaminantes_2.addAction(self.actionFactor_Conversi_n)
        self.menuContaminantes_2.addAction(self.actionFactor_Conversi_n_por_Aforo)
        self.menuContaminantes_2.addAction(self.actionMapAforoZona)
        self.menuC_lculo.addAction(self.actionCalcularEscenario)
        self.menuC_lculo.addSeparator()
        self.menuC_lculo.addAction(self.actionResultados)
        self.menuC_lculo.addAction(self.actionMapas)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuEdici_n.menuAction())
        self.menuBar.addAction(self.menuEscenario.menuAction())
        self.menuBar.addAction(self.menuContaminantes_2.menuAction())
        self.menuBar.addAction(self.menuZonas.menuAction())
        self.menuBar.addAction(self.menuDatos.menuAction())
        self.menuBar.addAction(self.menuC_lculo.menuAction())
        self.menuBar.addAction(self.menuInformes.menuAction())
        self.menuBar.addAction(self.menuVentanas.menuAction())

        self.retranslateUi(MainWindowClass)
        QtCore.QMetaObject.connectSlotsByName(MainWindowClass)

    def retranslateUi(self, MainWindowClass):
        MainWindowClass.setWindowTitle(_translate("MainWindowClass", "AIRE", None))
        self.menuArchivo.setTitle(_translate("MainWindowClass", "Archivo", None))
        self.menuEdici_n.setTitle(_translate("MainWindowClass", "Edición", None))
        self.menuVentanas.setTitle(_translate("MainWindowClass", "Ventanas", None))
        self.menuZonas.setTitle(_translate("MainWindowClass", "Zonas", None))
        self.menuEscenario.setTitle(_translate("MainWindowClass", "Maestro", None))
        self.menuInformes.setTitle(_translate("MainWindowClass", "Informes", None))
        self.menuDatos.setTitle(_translate("MainWindowClass", "Datos", None))
        self.menuContaminantes_2.setTitle(_translate("MainWindowClass", "Contaminantes", None))
        self.menuC_lculo.setTitle(_translate("MainWindowClass", "Cálculo", None))
        self.actionQuit.setText(_translate("MainWindowClass", "Salir", None))
        self.actionQuit.setShortcut(_translate("MainWindowClass", "Ctrl+Q", None))
        self.actionOpenConnection.setText(_translate("MainWindowClass", "Abre conexión", None))
        self.actionOpenConnection.setShortcut(_translate("MainWindowClass", "Ctrl+N", None))
        self.actionPreferencias.setText(_translate("MainWindowClass", "Preferencias", None))
        self.actionCopiar.setText(_translate("MainWindowClass", "Copiar", None))
        self.actionCopiar.setShortcut(_translate("MainWindowClass", "Ctrl+C", None))
        self.actionMotoresCalculo.setText(_translate("MainWindowClass", "Motores de cálculo", None))
        self.actionZonas.setText(_translate("MainWindowClass", "Zonas", None))
        self.actionEscenario.setText(_translate("MainWindowClass", "Escenario", None))
        self.actionOrigen.setText(_translate("MainWindowClass", "Origen", None))
        self.actionFuente.setText(_translate("MainWindowClass", "Fuente", None))
        self.actionTipo_Clasificaci_n.setText(_translate("MainWindowClass", "Tipo Clasificación", None))
        self.actionEquivalentes.setText(_translate("MainWindowClass", "Equivalentes", None))
        self.actionContaminante.setText(_translate("MainWindowClass", "Contaminante", None))
        self.actionFuenteClasificacion.setText(_translate("MainWindowClass", "Fuente Clasificacion", None))
        self.actionAforo.setText(_translate("MainWindowClass", "Aforo", None))
        self.actionPlantillas.setText(_translate("MainWindowClass", "Plantillas", None))
        self.actionTablas.setText(_translate("MainWindowClass", "Tablas", None))
        self.actionGraficos.setText(_translate("MainWindowClass", "Gráficos", None))
        self.actionGenerar_PDF.setText(_translate("MainWindowClass", "Generar PDF", None))
        self.actionFactor_Conversi_n.setText(_translate("MainWindowClass", "Factor Conversión", None))
        self.actionFactor_Conversi_n_por_Aforo.setText(_translate("MainWindowClass", "Factor Conversión por Aforo", None))
        self.actionValor_Dato.setText(_translate("MainWindowClass", "Toma en aforo", None))
        self.actionContaminante_Aforo.setText(_translate("MainWindowClass", "Contaminante en aforo", None))
        self.actionMapAforoZona.setText(_translate("MainWindowClass", "Factor por Aforo y Municipio", None))
        self.actionContaminanteZona.setText(_translate("MainWindowClass", "Contaminante en fuente", None))
        self.actionArbolClasificacion.setText(_translate("MainWindowClass", "Árbol Clasificacion", None))
        self.actionCalcularEscenario.setText(_translate("MainWindowClass", "Calcular escenario...", None))
        self.actionResultados.setText(_translate("MainWindowClass", "Resultados...", None))
        self.actionCombustibles.setText(_translate("MainWindowClass", "Combustibles", None))
        self.actionMapas.setText(_translate("MainWindowClass", "Mapas...", None))
        self.actionPrint.setText(_translate("MainWindowClass", "Imprimir...", None))
        self.actionPrint.setShortcut(_translate("MainWindowClass", "Ctrl+P", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindowClass = QtGui.QMainWindow()
    ui = Ui_MainWindowClass()
    ui.setupUi(MainWindowClass)
    MainWindowClass.show()
    sys.exit(app.exec_())

