# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zonalist.ui'
#
# Created: Fri Feb 21 12:06:31 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ZonaListClass(object):
    def setupUi(self, ZonaListClass):
        ZonaListClass.setObjectName(_fromUtf8("ZonaListClass"))
        ZonaListClass.resize(500, 376)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ZonaListClass.sizePolicy().hasHeightForWidth())
        ZonaListClass.setSizePolicy(sizePolicy)
        ZonaListClass.setMinimumSize(QtCore.QSize(500, 0))
        self.verticalLayout_2 = QtGui.QVBoxLayout(ZonaListClass)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tab = TTabWidget(ZonaListClass)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tablaNiveles = QtGui.QTableView(self.tab_4)
        self.tablaNiveles.setAlternatingRowColors(True)
        self.tablaNiveles.setObjectName(_fromUtf8("tablaNiveles"))
        self.verticalLayout.addWidget(self.tablaNiveles)
        self.tab.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabla = QtGui.QTableView(self.tab_5)
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setAlternatingRowColors(True)
        self.tabla.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_3.addWidget(self.tabla)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.anade = QtGui.QPushButton(self.tab_5)
        self.anade.setObjectName(_fromUtf8("anade"))
        self.horizontalLayout.addWidget(self.anade)
        self.edita = QtGui.QPushButton(self.tab_5)
        self.edita.setEnabled(False)
        self.edita.setObjectName(_fromUtf8("edita"))
        self.horizontalLayout.addWidget(self.edita)
        self.elimina = QtGui.QPushButton(self.tab_5)
        self.elimina.setEnabled(False)
        self.elimina.setObjectName(_fromUtf8("elimina"))
        self.horizontalLayout.addWidget(self.elimina)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tab.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.tab_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.escenario = TComboBox(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.escenario.sizePolicy().hasHeightForWidth())
        self.escenario.setSizePolicy(sizePolicy)
        self.escenario.setObjectName(_fromUtf8("escenario"))
        self.horizontalLayout_3.addWidget(self.escenario)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.tablaDatos = QtGui.QTableView(self.tab_6)
        self.tablaDatos.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablaDatos.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tablaDatos.setAlternatingRowColors(True)
        self.tablaDatos.setObjectName(_fromUtf8("tablaDatos"))
        self.verticalLayout_5.addWidget(self.tablaDatos)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.guardaDatos = QtGui.QPushButton(self.tab_6)
        self.guardaDatos.setObjectName(_fromUtf8("guardaDatos"))
        self.horizontalLayout_2.addWidget(self.guardaDatos)
        self.descartaDatos = QtGui.QPushButton(self.tab_6)
        self.descartaDatos.setObjectName(_fromUtf8("descartaDatos"))
        self.horizontalLayout_2.addWidget(self.descartaDatos)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.anadeDatos = QtGui.QPushButton(self.tab_6)
        self.anadeDatos.setObjectName(_fromUtf8("anadeDatos"))
        self.horizontalLayout_2.addWidget(self.anadeDatos)
        self.eliminaDatos = QtGui.QPushButton(self.tab_6)
        self.eliminaDatos.setObjectName(_fromUtf8("eliminaDatos"))
        self.horizontalLayout_2.addWidget(self.eliminaDatos)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.tab.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.escenarioParam = TComboBox(self.tab_2)
        self.escenarioParam.setObjectName(_fromUtf8("escenarioParam"))
        self.horizontalLayout_5.addWidget(self.escenarioParam)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.tablaParametros = QtGui.QTableView(self.tab_2)
        self.tablaParametros.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablaParametros.setObjectName(_fromUtf8("tablaParametros"))
        self.verticalLayout_4.addWidget(self.tablaParametros)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.guardaParametros = QtGui.QPushButton(self.tab_2)
        self.guardaParametros.setObjectName(_fromUtf8("guardaParametros"))
        self.horizontalLayout_4.addWidget(self.guardaParametros)
        self.descartaParametros = QtGui.QPushButton(self.tab_2)
        self.descartaParametros.setObjectName(_fromUtf8("descartaParametros"))
        self.horizontalLayout_4.addWidget(self.descartaParametros)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.anadeParametros = QtGui.QPushButton(self.tab_2)
        self.anadeParametros.setObjectName(_fromUtf8("anadeParametros"))
        self.horizontalLayout_4.addWidget(self.anadeParametros)
        self.eliminaParametros = QtGui.QPushButton(self.tab_2)
        self.eliminaParametros.setObjectName(_fromUtf8("eliminaParametros"))
        self.horizontalLayout_4.addWidget(self.eliminaParametros)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tab.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab)
        self.clipboardDatos = QtGui.QAction(ZonaListClass)
        self.clipboardDatos.setObjectName(_fromUtf8("clipboardDatos"))
        self.clipboardParametros = QtGui.QAction(ZonaListClass)
        self.clipboardParametros.setObjectName(_fromUtf8("clipboardParametros"))
        self.label.setBuddy(self.escenario)
        self.label_2.setBuddy(self.escenarioParam)

        self.retranslateUi(ZonaListClass)
        self.tab.setCurrentIndex(0)
        QtCore.QObject.connect(self.tablaDatos, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), ZonaListClass.showContextMenu)
        QtCore.QObject.connect(self.tablaParametros, QtCore.SIGNAL(_fromUtf8("customContextMenuRequested(QPoint)")), ZonaListClass.showContextMenu)
        QtCore.QMetaObject.connectSlotsByName(ZonaListClass)
        ZonaListClass.setTabOrder(self.tablaNiveles, self.tab)
        ZonaListClass.setTabOrder(self.tab, self.tabla)
        ZonaListClass.setTabOrder(self.tabla, self.anade)
        ZonaListClass.setTabOrder(self.anade, self.edita)
        ZonaListClass.setTabOrder(self.edita, self.elimina)
        ZonaListClass.setTabOrder(self.elimina, self.escenario)
        ZonaListClass.setTabOrder(self.escenario, self.tablaDatos)
        ZonaListClass.setTabOrder(self.tablaDatos, self.anadeDatos)
        ZonaListClass.setTabOrder(self.anadeDatos, self.eliminaDatos)
        ZonaListClass.setTabOrder(self.eliminaDatos, self.guardaDatos)
        ZonaListClass.setTabOrder(self.guardaDatos, self.descartaDatos)
        ZonaListClass.setTabOrder(self.descartaDatos, self.escenarioParam)
        ZonaListClass.setTabOrder(self.escenarioParam, self.tablaParametros)
        ZonaListClass.setTabOrder(self.tablaParametros, self.anadeParametros)
        ZonaListClass.setTabOrder(self.anadeParametros, self.eliminaParametros)
        ZonaListClass.setTabOrder(self.eliminaParametros, self.guardaParametros)
        ZonaListClass.setTabOrder(self.guardaParametros, self.descartaParametros)

    def retranslateUi(self, ZonaListClass):
        ZonaListClass.setWindowTitle(_translate("ZonaListClass", "Form", None))
        self.tab.setTabText(self.tab.indexOf(self.tab_4), _translate("ZonaListClass", "Niveles", None))
        self.anade.setText(_translate("ZonaListClass", "Añadir...", None))
        self.edita.setText(_translate("ZonaListClass", "Editar...", None))
        self.elimina.setText(_translate("ZonaListClass", "Eliminar", None))
        self.tab.setTabText(self.tab.indexOf(self.tab_5), _translate("ZonaListClass", "Zonas", None))
        self.label.setText(_translate("ZonaListClass", "Escenario", None))
        self.guardaDatos.setText(_translate("ZonaListClass", "Guardar", None))
        self.descartaDatos.setText(_translate("ZonaListClass", "Descartar", None))
        self.anadeDatos.setText(_translate("ZonaListClass", "Añadir", None))
        self.eliminaDatos.setText(_translate("ZonaListClass", "Eliminar", None))
        self.tab.setTabText(self.tab.indexOf(self.tab_6), _translate("ZonaListClass", "Datos", None))
        self.label_2.setText(_translate("ZonaListClass", "Escenario", None))
        self.guardaParametros.setText(_translate("ZonaListClass", "Guardar", None))
        self.descartaParametros.setText(_translate("ZonaListClass", "Descartar", None))
        self.anadeParametros.setText(_translate("ZonaListClass", "Añadir", None))
        self.eliminaParametros.setText(_translate("ZonaListClass", "Eliminar", None))
        self.tab.setTabText(self.tab.indexOf(self.tab_2), _translate("ZonaListClass", "Parámetros", None))
        self.clipboardDatos.setText(_translate("ZonaListClass", "Insertar desde el portapapeles", None))
        self.clipboardParametros.setText(_translate("ZonaListClass", "Insertar desde el portapapeles...", None))

from ts import TTabWidget, TComboBox
from widgets.datalist import DataList

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ZonaListClass = QtGui.DataList()
    ui = Ui_ZonaListClass()
    ui.setupUi(ZonaListClass)
    ZonaListClass.show()
    sys.exit(app.exec_())

